const {test} = require('node:test');
const assert = require('node:assert/strict');
const {processUpload, normalizeOptions, verifyPreheats} = require('../advance_preheat');
function fixture() {return [
  '; HEADER_BLOCK_START','; BambuStudio 02.08.02.61','; HEADER_BLOCK_END',
  '; CONFIG_BLOCK_START','; CONFIG_BLOCK_END','; EXECUTABLE_BLOCK_START',
  'G90','M83','T0','; MACHINE_START_GCODE_END','G1 X0 Y0 F600',
  'G1 X500 E5','M104 S70 T0 ; cooldown previous extruder',
  'M109 S230 T1','M400','T1','SM_PRINT_PREEXTRUDE_FILAMENT INDEX=1',
  'G1 X500 Y0 F600','G1 X1000 E5',
  'M104 T0 S220 N0 ;Wipe tower reheat before wipe',
  'M104 S70 T1 ; cooldown previous extruder','M109 S220 T0','T0',
  'PRINT_END','; EXECUTABLE_BLOCK_END'].join('\n');}
test('preserves every command except legacy reheats and adds exact temperatures',()=>{
  const original=fixture(), {content,report}=processUpload(original);
  const clean=s=>s.split(/\r?\n/).filter(l=>!l.includes('U1_ADVANCE_PREHEAT')&&!l.includes(';Wipe tower reheat before wipe'));
  assert.deepEqual(clean(content),clean(original));
  assert.equal(report.switches,2);assert.equal(verifyPreheats(content),2);
  assert.match(content,/M104 S230 T1 ; U1_ADVANCE_PREHEAT/);
  assert.match(content,/M104 S220 T0 ; U1_ADVANCE_PREHEAT/);
});
test('short reuse schedules after previous cooldown, which cannot cancel it',()=>{
  const {content,report}=processUpload(fixture().replace('G1 X1000 E5','G1 X501 E5'));
  const row=report.rows[1];assert.equal(row.limitedByRecentUse,true);
  assert(row.originalInsertionLine > fixture().split('\n').findIndex(l=>l.startsWith('M104 S70 T0'))+1);
  assert.equal(verifyPreheats(content),2);
});
test('already processed input is validated and never processed twice',()=>{
 const first=processUpload(fixture());const second=processUpload(first.content);
 assert.equal(second.content,first.content);assert.equal(second.report.status,'already_processed');
 assert.throws(()=>processUpload(first.content.replace('M109 S230 T1','M104 S70 T1\nM109 S230 T1')),/cancelled/);
});
test('same-temperature repeats preserve preheating; real target changes invalidate it',()=>{
 const first=processUpload(fixture());
 const repeated=first.content.replace('M109 S230 T1','M104 T1 S230 N0\r\nM109 S230 T1');
 assert.equal(verifyPreheats(repeated),2);
 assert.equal(processUpload(repeated).report.status,'already_processed');
 const changed=first.content.replace('M109 S230 T1','M104 T1 S70\r\nM104 T1 S230 N0\r\nM109 S230 T1');
 assert.throws(()=>verifyPreheats(changed),/cancelled/);
 const absent=fixture().replace('M109 S230 T1','M104 T1 S230 N0\nM109 S230 T1');
 assert.throws(()=>verifyPreheats(absent),/missing/);
});
test('disabled and unrelated slicers are unchanged',()=>{
 assert.equal(processUpload(fixture(),{enabled:false}).content,fixture());
 const orca='; generated by Snapmaker Orca\nM104 S220 T1 ; preheat T1 time: 30s';
 assert.equal(processUpload(orca).content,orca);
});
test('invalid settings and unsupported commands fail before upload',()=>{
 assert.throws(()=>normalizeOptions({enabled:'false'}));
 for(const n of [0,121,NaN,Infinity])assert.throws(()=>normalizeOptions({leadSeconds:n}));
 assert.throws(()=>processUpload(fixture().replace('T1\nSM_','T256\nSM_')),/logical tool ID/);
 assert.throws(()=>processUpload(fixture().replace('G90','G20')),/Inch/);
 assert.throws(()=>processUpload(fixture().replace('; MACHINE_START_GCODE_END','; unknown')),/boundary/);
});
test('existing alternate scheduler is not duplicated',()=>{
 assert.throws(()=>processUpload(fixture()+'\nM104 S220 T1 ; preheat T1 time: 30s'),/already present/);
});
test('scheduled heating cannot precede further extrusion on the same active tool',()=>{
 const unsafe=fixture().replace('G1 X500 E5','M104 S220 T0 ; U1_ADVANCE_PREHEAT\nG1 X500 E5');
 assert.throws(()=>verifyPreheats(unsafe),/still extruding/);
});
test('arc endpoints, relative motion, and speed overrides are accepted without editing moves',()=>{
 const original=fixture().replace('G1 X500 E5','M220 B\nM220 S50\nG91\nG1 X100 E5\nG3 X10 Y10 I5 J5 F600\nG90\nM220 R\nG1 X500 E5');
 const result=processUpload(original);assert.equal(result.report.switches,2);assert.equal(verifyPreheats(result.content),2);
});
module.exports={fixture};

test('sparse logical slots retain their IDs and exact per-filament temperatures',()=>{
 const original=fixture().replaceAll('T0','T7').replaceAll('T1','T5').replaceAll('INDEX=1','INDEX=5');
 const {content,report}=processUpload(original);
 assert.equal(report.leadSeconds,30);
 assert.match(content,/M104 S230 T5 ; U1_ADVANCE_PREHEAT/);
 assert.match(content,/M104 S220 T7 ; U1_ADVANCE_PREHEAT/);
 assert.equal(verifyPreheats(content),2);
 const clean=s=>s.split(/\r?\n/).filter(l=>!l.includes('U1_ADVANCE_PREHEAT')&&!l.includes(';Wipe tower reheat before wipe'));
 assert.deepEqual(clean(content),clean(original));
});
test('more than four logical filaments can reach the mapping dialog',()=>{
 assert.equal(processUpload(fixture()+'\nT2\nT5\nT7').report.switches,2);
});
test('saved heating lead remains respected',()=>{
 assert.equal(processUpload(fixture(),{leadSeconds:40}).report.leadSeconds,40);
});
test('pauses are preserved and post-resume heating never crosses the pause',()=>{
 const {countPauses}=require('../advance_preheat');
 for(const pause of ['PAUSE','M600','M0','M1']){
   const source=fixture().replace('M109 S230 T1',`  ${pause} ; replace two spools\nM109 S230 T1`);
   const result=processUpload(source),lines=result.content.split(/\r?\n/);
   const at=lines.findIndex(l=>l.trim().startsWith(pause+' ;'));
   assert(at>=0);assert.equal(countPauses(result.content),1);
   assert(lines.findIndex(l=>l.includes('M104 S230 T1 ; U1_ADVANCE_PREHEAT'))>at);
   assert.equal(verifyPreheats(result.content),2);
   assert.match(result.content,new RegExp('  '+pause+' ; replace two spools'));
   const invalid=result.content.replace(/^M104 S230 T1 ; U1_ADVANCE_PREHEAT[^\r\n]*\r?\n/m,'')
      .replace('  '+pause,'M104 S230 T1 ; U1_ADVANCE_PREHEAT\r\n  '+pause);
   assert.throws(()=>verifyPreheats(invalid),/missing or cancelled/);
 }
 assert.equal(countPauses('; PAUSE\n; custom_gcode = M600\nM104 S0\nPAUSE_BASE'),0);
});
test('each pause establishes its own heating boundary',()=>{
 const source=fixture().replace('M109 S230 T1','PAUSE\nM109 S230 T1').replace('M109 S220 T0','M600\nM109 S220 T0');
 const result=processUpload(source);
 assert.match(result.content,/PAUSE\r\nM104 S230 T1 ; U1_ADVANCE_PREHEAT/);
 assert.match(result.content,/M600\r\nM104 S220 T0 ; U1_ADVANCE_PREHEAT/);
});
