const {test}=require('node:test'),assert=require('node:assert/strict');
const {prepareTouchscreenFormat,executableLines,MARKER}=require('../touchscreen_format');
const {processUpload,verifyPreheats}=require('../advance_preheat');
const {prepareSharedPrint,restoreHeating}=require('../shared_preheat');
const {usedSlotsFromGcode}=require('../file_filaments');
const printCommands=content=>executableLines(content.slice(content.indexOf('; MACHINE_START_GCODE_END')+'; MACHINE_START_GCODE_END'.length));
function fixture(){return [
 '; HEADER_BLOCK_START','; BambuStudio 02.08.02.61','; filament: 2,6','; total filament length [mm] : 100,200','; total filament weight [g] : 0.3,0.6','; HEADER_BLOCK_END',
 '; CONFIG_BLOCK_START','; filament_type = PLA;PLA;PLA;PLA;PLA;PLA','; CONFIG_BLOCK_END',
 '; THUMBNAIL_BLOCK_START','; thumbnail data','; THUMBNAIL_BLOCK_END',
 '; EXECUTABLE_BLOCK_START','PRINT_START','M140 S65','M83','T1','SM_PRINT_CHECK_SWITCH_EXTRUDER',
 '; MACHINE_START_GCODE_END',';BEFORE_LAYER_CHANGE','; FEATURE: Outer wall','G1 X0 Y0 F600','G1 X500 E5',
 'PAUSE ; replace spools','M104 S70 T1 ; cooldown previous extruder','M109 S230 T5','T5',
 '; FEATURE: Inner wall','G1 X0 Y0 F600','G1 X500 E5','PRINT_END','; EXECUTABLE_BLOCK_END'].join('\n');}
test('automatic conversion preserves sliced commands, temperatures, pauses, and logical IDs',()=>{
 const source=processUpload(fixture()).content,result=prepareTouchscreenFormat(source);
 assert.equal(result.status,'prepared');assert.deepEqual(printCommands(result.content),printCommands(source));
 assert.deepEqual(usedSlotsFromGcode(result.content),[1,5]);assert.equal(verifyPreheats(result.content),1);
 assert(result.content.includes(';TYPE:Outer wall'));assert(!/^; FEATURE:/m.test(result.content));
 assert(result.content.indexOf('; CONFIG_BLOCK_START')>result.content.indexOf('; EXECUTABLE_BLOCK_END'));
 assert(result.content.indexOf('; THUMBNAIL_BLOCK_START')<result.content.indexOf('; EXECUTABLE_BLOCK_START'));
 assert.equal(prepareTouchscreenFormat(result.content).content,result.content);
});
test('converted files can regenerate shared heating without changing their format',()=>{
 const converted=prepareTouchscreenFormat(fixture()).content;
 const result=prepareSharedPrint(converted,[[1,0],[5,0]],{});
 assert.equal(verifyPreheats(result.content,new Map([[1,0],[5,0]])),1);
 assert(result.content.includes(MARKER));assert(result.content.includes('PAUSE ; replace spools'));
 assert(!restoreHeating(result.content).includes('U1_ADVANCE_PREHEAT'));
 assert(restoreHeating(result.content).includes('M104 S70 T1 ; cooldown previous extruder'));
});
test('native identity and footer usage preserve sparse logical slot positions',()=>{
 const result=prepareTouchscreenFormat(fixture()).content;
 assert.match(result,/^; generated by Snapmaker Orca 2\.4\.0 on \d{4}-\d{2}-\d{2} at /m);
 assert(!/^; BambuStudio\b/m.test(result));
 assert.match(result,/; U1 source slicer: Bambu Studio 02\.08\.02\.61/);
 assert.match(result,/; filament used \[mm\] = 0\.00, 100\.00, 0\.00, 0\.00, 0\.00, 200\.00/);
 assert.match(result,/; total filament used \[g\] = 0\.90/);
 assert(result.indexOf('; filament used [mm]')>result.indexOf('; EXECUTABLE_BLOCK_END'));
 assert(result.indexOf('; filament used [mm]')<result.indexOf('; CONFIG_BLOCK_START'));
 assert.equal(processUpload(processUpload(result).content).content,processUpload(result).content);
});
test('version 7 files upgrade their metadata without rebuilding startup or printing commands',()=>{
 const current=prepareTouchscreenFormat(fixture()).content;
 const old=current.replace(MARKER,'; U1_TOUCHSCREEN_FORMAT v2')
   .replace(/^; generated by[^\r\n]*\r?\n; U1 compatibility[^\r\n]*\r?\n; U1 source slicer: Bambu Studio ([^\r\n]+)/m,'; BambuStudio $1')
   .replace(/^; filament used \[mm\][\s\S]*?(?=; CONFIG_BLOCK_START)/m,'');
 const upgraded=prepareTouchscreenFormat(old);
 assert.equal(upgraded.status,'metadata_upgraded');
 assert.deepEqual(executableLines(upgraded.content),executableLines(old));
 assert.match(upgraded.content,/; filament used \[mm\]/);
 assert.equal(prepareTouchscreenFormat(upgraded.content).content,upgraded.content);
});
test('missing or inconsistent usage fails before advertising touchscreen conversion',()=>{
 for(const source of [fixture().replace('; total filament weight [g] : 0.3,0.6',''),
   fixture().replace('; total filament length [mm] : 100,200','; total filament length [mm] : 100,200,300')])
  assert.throws(()=>prepareTouchscreenFormat(source),/statistics/);
});
test('startup keeps bed offsets and primes at the first material temperature',()=>{
 const source=fixture().replace('; MACHINE_START_GCODE_END',
   'M109 S215\nG28 Z Z_OFFSET -0.07\nBED_MESH_CALIBRATE PROBE_COUNT=11,11 Z_OFFSET=-0.07\n; MACHINE_START_GCODE_END');
 const converted=prepareTouchscreenFormat(source).content;
 const startup=converted.split('; MACHINE_START_GCODE_END')[0];
 assert.match(startup,/G28 Z Z_OFFSET -0\.07/);
 assert.match(startup,/BED_MESH_CALIBRATE PROBE_COUNT=11,11 Z_OFFSET=-0\.07/);
 assert.match(startup,/G0 X85 Y1 Z2 F18000\nM109 S215/);
 assert(!startup.includes('M109 S230'));
 assert.deepEqual([...startup.matchAll(/^M104 S0 T(\d+) A0$/gm)].map(m=>Number(m[1])),[0,1,2,3]);
 assert.deepEqual(printCommands(converted),printCommands(source));
});
test('legacy executable-end positions are normalized without losing the body',()=>{
 const source=fixture().replace('; EXECUTABLE_BLOCK_END','').replace('; MACHINE_START_GCODE_END','; EXECUTABLE_BLOCK_END\n; MACHINE_START_GCODE_END');
 const result=prepareTouchscreenFormat(source).content;
 assert(result.indexOf('; EXECUTABLE_BLOCK_END')>result.indexOf('PRINT_END'));
 assert.deepEqual(printCommands(result),printCommands(source));
});
test('unrelated slicers stay unchanged and malformed metadata blocks are rejected',()=>{
 const orca='; generated by OrcaSlicer\n;TYPE:Outer wall\nG1 X1 E1';
 assert.equal(prepareTouchscreenFormat(orca).content,orca);
 for(const source of [fixture().replace('; HEADER_BLOCK_END',''),fixture().replace('; CONFIG_BLOCK_END','G1 X999\n; CONFIG_BLOCK_END'),fixture()+'\n; EXECUTABLE_BLOCK_END',fixture().replace('SM_PRINT_CHECK_SWITCH_EXTRUDER','')])
  assert.throws(()=>prepareTouchscreenFormat(source),/invalid|Unexpected|one executable|printer profile/);
});


test('sparse logical tools initialize each physical head once',()=>{
 const converted=prepareTouchscreenFormat(fixture()).content;
 const startup=converted.split('; MACHINE_START_GCODE_END')[0];
 for(const macro of ['SM_PRINT_EXTRUDER_PREHEAT','SM_PRINT_AUTO_FEED','SM_PRINT_FLOW_CALIBRATE'])
  assert.deepEqual([...startup.matchAll(new RegExp('^'+macro+' EXTRUDER=(\\d+)','gm'))].map(m=>Number(m[1])),[0,1,2,3]);
 const broken=converted.replace('SM_PRINT_AUTO_FEED EXTRUDER=3','SM_PRINT_AUTO_FEED EXTRUDER=5');
 const repaired=prepareTouchscreenFormat(broken);
 assert.equal(repaired.status,'startup_repaired');
 assert.deepEqual(printCommands(repaired.content),printCommands(broken));
 assert.equal(repaired.content,converted);
});
