// Use the author's Orca startup conversion, preserving the entire sliced body.
const {convertGcodeContent}=require('./slice_agent');
const {isBambuU1}=require('./advance_preheat');
const {usedSlotsFromGcode}=require('./file_filaments');
const MARKER='; U1_TOUCHSCREEN_FORMAT v3';
function executableLines(content){return content.split(/\r?\n/).map(l=>l.split(';')[0].trim()).filter(Boolean);}
function completeTouchscreenMetadata(content){
  const lines=content.split(/\r?\n/),value=prefix=>lines.find(l=>l.startsWith(prefix))?.slice(prefix.length).trim();
  const headerSlots=value('; filament:');
  const slots=headerSlots ? headerSlots.split(',').map(s=>Number(s.trim())-1) : usedSlotsFromGcode(content);
  if(!slots.length || new Set(slots).size!==slots.length || slots.some(s=>!Number.isInteger(s)||s<0||s>31))
    throw Error('Invalid used-filament statistics.');
  const diameters=value('; filament_diameter:')?.split(',').map(Number)||[];
  const count=Math.max(slots.length,Math.max(...slots)+1,diameters.length,(value('; filament_type = ')||'').split(';').length);
  const numbers=prefix=>{
    const raw=value(prefix);
    if(raw===undefined)throw Error('Missing filament usage statistics required for touchscreen conversion.');
    const values=raw.split(',').map(Number);
    if(values.some(n=>!Number.isFinite(n)||n<0))throw Error('Invalid filament usage statistics.');
    const result=Array(count).fill(0);
    if(values.length===slots.length)slots.forEach((slot,i)=>result[slot]=values[i]);
    else if(values.length===count)values.forEach((n,i)=>result[i]=slots.includes(i)?n:0);
    else throw Error('Filament statistics do not match the used project slots.');
    return result;
  };
  const length=numbers('; total filament length [mm] :'),weight=numbers('; total filament weight [g] :');
  const volume=length.map((mm,i)=>{
    const d=diameters[i]??1.75;
    if(!Number.isFinite(d)||d<=0)throw Error('Invalid filament diameter.');
    return mm*Math.PI*(d/2)**2/1000;
  });
  const stats=[];
  for(const [unit,values] of [['mm',length],['cm3',volume],['g',weight]])
    stats.push('; filament used ['+unit+'] = '+values.map(n=>n.toFixed(2)).join(', '));
  stats.push('; total filament used [g] = '+weight.reduce((a,b)=>a+b,0).toFixed(2));
  const layers=value('; total layer number:');
  if(layers!==undefined)stats.push('; total layers count = '+layers);
  const estimated=lines.find(l=>l.startsWith('; estimated printing time (normal mode) ='));
  if(estimated)stats.push(estimated);
  if(!content.includes('; CONFIG_BLOCK_START'))throw Error('Touchscreen conversion requires a settings block.');
  let result=content.replace('; CONFIG_BLOCK_START',stats.join('\n')+'\n\n; CONFIG_BLOCK_START');
  // The successful physical test used both native identification and footer
  // statistics. Preserve provenance separately so our heating still recognizes it.
  const timestamp=new Date().toISOString().slice(0,19).replace('T',' at ');
  result=result.replace(/^; BambuStudio ([^\r\n]+)/m,
    '; generated by Snapmaker Orca 2.4.0 on '+timestamp+'\n; U1 compatibility conversion; sliced by Bambu Studio\n; U1 source slicer: Bambu Studio $1');
  result=result.replace(/^; U1_TOUCHSCREEN_FORMAT v2\s*$/m,MARKER);
  if(!result.includes(MARKER))result=result.replace('; HEADER_BLOCK_END',MARKER+'\n; HEADER_BLOCK_END');
  if(JSON.stringify(executableLines(result))!==JSON.stringify(executableLines(content)))
    throw Error('Touchscreen metadata changed executable commands.');
  return result;
}
function repairPhysicalStartup(content){
  const end=content.indexOf('; MACHINE_START_GCODE_END');
  if(end<0)return content;
  let startup=content.slice(0,end);
  const block=/^SM_PRINT_EXTRUDER_PREHEAT EXTRUDER=\d+ TEMP=140\r?\n(?:SM_PRINT_(?:EXTRUDER_PREHEAT EXTRUDER=\d+ TEMP=140|AUTO_FEED EXTRUDER=\d+|FLOW_CALIBRATE EXTRUDER=\d+)\r?\n)*/m;
  const physical=[0,1,2,3].map(n=>'SM_PRINT_EXTRUDER_PREHEAT EXTRUDER='+n+' TEMP=140').concat([0,1,2,3].flatMap(n=>['SM_PRINT_AUTO_FEED EXTRUDER='+n,'SM_PRINT_FLOW_CALIBRATE EXTRUDER='+n])).join('\n')+'\n';
  startup=startup.replace(block,physical);
  return startup+content.slice(end);
}
function prepareTouchscreenFormat(content){
  if(!isBambuU1(content))return {content,status:'other_slicer'};
  if(content.includes(MARKER)){const repaired=repairPhysicalStartup(content);return {content:repaired,status:repaired===content?'already_prepared':'startup_repaired'};}
  if(content.includes('; U1_TOUCHSCREEN_FORMAT v2'))return {content:completeTouchscreenMetadata(content),status:'metadata_upgraded'};
  if(!/^;\s*FEATURE:/m.test(content))return {content,status:'existing_or_unknown_format'};
  if(!content.includes('; MACHINE_START_GCODE_END'))throw Error('Automatic conversion requires the supported U1 startup boundary.');
  const startup=content.slice(content.indexOf('; EXECUTABLE_BLOCK_START'),content.indexOf('; MACHINE_START_GCODE_END'));
  if(!/^PRINT_START\s*$/m.test(startup) || !/^SM_PRINT_CHECK_SWITCH_EXTRUDER\s*$/m.test(startup))
    throw Error('Automatic conversion requires the Snapmaker U1 printer profile.');
  for(const line of content.split(/\r?\n/)) {
    const code=line.split(';')[0].trim();
    if(/^T\d+\b/.test(code) && (!/^T\d+$/.test(code) || Number(code.slice(1))>31))
      throw Error('Invalid logical tool ID (supported slots: 1–32).');
  }
  let body=content;
  function take(name,required=false){
    const start='; '+name+'_BLOCK_START',end='; '+name+'_BLOCK_END';
    const a=body.indexOf(start),b=body.indexOf(end);
    if(a<0&&b<0&&!required)return '';
    if(a<0||b<a||body.indexOf(start,a+start.length)>=0||body.indexOf(end,b+end.length)>=0)
      throw Error('Automatic conversion found invalid '+name+' blocks.');
    const block=body.slice(a,b+end.length);
    if(executableLines(block).length)throw Error('Unexpected executable commands in '+name+' metadata.');
    body=body.slice(0,a)+body.slice(b+end.length);
    return block;
  }
  let header=take('HEADER',true),thumb=take('THUMBNAIL'),config=take('CONFIG');
  for(const suffix of ['START','END']){
    const marker='; EXECUTABLE_BLOCK_'+suffix;
    if(body.split(marker).length!==2)throw Error('Automatic conversion requires one executable block.');
  }
  const canonical=[header,thumb,config,body].filter(Boolean).join('\n');
  let result=convertGcodeContent(canonical,{automatic:true}).content;
  result=completeTouchscreenMetadata(result);
  const printBody=text=>text.slice(text.indexOf('; MACHINE_START_GCODE_END')+'; MACHINE_START_GCODE_END'.length);
  const before=executableLines(printBody(body)),after=executableLines(printBody(result));
  if(before.length!==after.length||before.some((line,i)=>line!==after[i]))throw Error('Automatic conversion changed sliced print commands.');
  return {content:result,status:'prepared'};
}
module.exports={prepareTouchscreenFormat,MARKER,executableLines};
